hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
hibernate.hbm2ddl.auto=update
hibernate.show_sql=true
hibernate.format_sql=true

javax.persistence.jdbc.url=jdbc:postgresql://localhost:5432/acaiteria 
javax.persistence.jdbc.user=admin
javax.persistence.jdbc.password=admin
javax.persistence.jdbc.driver=org.postgresql.Driver
